service: wedding-invitation-ever-ever-after
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x
  profile: default
  region: ap-northeast-2

functions:
  http-api:
    handler: .build/src/server.handler
    url:
      cors: true
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-common-excludes
