service: wedding-invitation-ever-ever-after
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: default
  region: 

functions:
  http-api:
    handler: .build/src/server.handler
    events:
      - httpApi: '*'
  rest-api:
    handler: .build/src/server.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-plugin-typescript
  - serverless-offline