service: wedding-invitation-ever-ever-after
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs16.x
  profile: default
  region: ap-northeast-2

functions:
  http-api:
    handler: .build/src/server.handler
    url:
      cors: true
    events:
      - httpApi: '*'
  rest-api:
    handler: .build/src/server.handler
    url:
      cors: true
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-common-excludes

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDefault5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"